<?php

namespace src\controllers;

use src\libraries\LogManager;

/**
 * This is the generic class for all controller post requests
 */
abstract class PostController {
    /**
     * Array of errors
     * @var Array $errors
     */
    protected Array $errors;

    /**
     * The log manager for log options
     * @var LogManager $logger
     */
    protected LogManager $logger;

    public function __construct() {
        $this->errors = [];
        $this->logger = new LogManager('Controllers');
    }

    /**
     * Return the errors generated by the controllers
     */
    public function getErrors() {
        return $this->errors;
    }
}