<?php

namespace exam\src\controllers;

/**
 * This is the generic class for all controller post requests
 */
abstract class PostController {
    /**
     * Array of errors
     * @var Array $errors
     */
    protected Array $errors;

    public function __construct() {
        $this->errors = [];
    }

    /**
     * Return the errors generated by the controllers
     */
    public function getErrors() {
        return $this->errors;
    }
}