/*
 * This is the first SQL file to execute, this one will create:
 * - Database
 * - Tables
 * 
 * If you want to have a specific user for this database, 
 * you can execute SQLMyUser.sql after this
 */
SET NAMES UTF8;
CREATE DATABASE IF NOT EXISTS biblioteca;
USE biblioteca;

DROP TABLE IF EXISTS prestamos;
DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS usuarios;

CREATE TABLE IF NOT EXISTS books (id INT AUTO_INCREMENT NOT NULL, titulo VARCHAR(60) NOT NULL, editorial VARCHAR(25) DEFAULT NULL, autor VARCHAR(25) DEFAULT NULL, genero VARCHAR(20) NOT NULL, pais VARCHAR(20) DEFAULT NULL, nPaginas INT DEFAULT NULL, year DATETIME DEFAULT NULL, precio DOUBLE PRECISION NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
CREATE TABLE IF NOT EXISTS usuarios (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(15) NOT NULL, apellidos VARCHAR(25) DEFAULT NULL, dni VARCHAR(9) NOT NULL, domicilio VARCHAR(50) DEFAULT NULL, poblacion VARCHAR(30) DEFAULT NULL, provincia VARCHAR(20) DEFAULT NULL, birthday DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS prestamos (id INT AUTO_INCREMENT NOT NULL, libro_id INT NOT NULL, usuario_id INT NOT NULL, completionDate DATETIME NOT NULL, maxDelayDate DATETIME NOT NULL, returnDate DATETIME NOT NULL, INDEX IDX_4849844FB91B4A02 (libro_id), INDEX IDX_4849844F629AF449 (usuario_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
ALTER TABLE prestamos ADD CONSTRAINT FK_PRESTAMOS_LIBROS FOREIGN KEY (libro_id) REFERENCES books (id);
ALTER TABLE prestamos ADD CONSTRAINT FK_PRESTAMOS_USUARIOS FOREIGN KEY (usuario_id) REFERENCES usuarios (id);